INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('2', 'Jehan de Saint-Quentin', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('3', 'Simon', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('4', 'Watriquet de Couvins', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('5', 'Ferrant', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('6', 'Jean de Meung', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('7', 'Nicole Bozon', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('8', 'Rutebeuf', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('9', 'Archevesque', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('10', 'Hue Archevesque', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('11', 'Rabbi Jacob, fils de Juda de Lotra', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('12', 'Moniot', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('13', 'Moniot de Paris', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('14', 'Saint Fran\1\1ois d''Assise', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('15', 'Saint Fran\1\1ois d Assise', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('16', 'Pierre de Langtoft', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('17', 'Nicole Oresme', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('18', 'Simon de Kermerthin', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('19', 'Clerc de Voudoi', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('20', 'Clopin', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('21', 'Philippe de R\1\1my, sire de Beaumanoir', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('22', 'Geoffroi de Paris', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('23', 'Gilles le Muisit', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('24', 'Jean Bodel', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('25', 'Gautier l''Epicier', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('26', 'Gautier l Epicier', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('27', 'Martin da Canal', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('28', 'Estienne Lanquelier', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('29', 'Plantefolie', '', '', 'clerc', '', '');
INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('30', 'Jehan Durpain', '', '', '', '', '');
INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('31', 'Asselin du Pont', '', '', 'bourgeois', '', '');
INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('32', 'Lambelin', '', '', 'clerc', '', '');
INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('33', 'Robin de la Val\1\1e', '', '', '', '', '');
INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('34', 'Henreis de Heis', '', '', '', '', '');
INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('35', 'Michelet Petitpain', '', '', '', '', '');
INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('36', 'Margueron du Pont Rengmont', '', '', '', '', '');
INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('37', 'Lowis de Piti\1\1', '', '', 'clerc', '', '');
INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('38', 'Adam de la Halle', '', '', '', '', '');
INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('39', 'Achile Caulier', '', '', 'bourgeois', '1420', '1440');
INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('40', 'Guillaume de Digulleville', '1295', '1380', 'moine', '1320', '1380');
INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('41', 'Renclus de Molliens', '', '', 'moine', '', '');
INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('42', 'Jean le Rigol\1\1', '', '', 'jongleur', '', '');
INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('43', 'Jean Chapuis', '', '', '', '', '');
INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('45', 'Renaut de Louhens', '', '', '', '', '');
INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('46', 'Baude Fastoul', '', '', 'jongleur', '', '');
INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('47', 'Guillaume de Saint-Amour', '', '', '', '', '');
INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('48', 'Robert Le Clerc', '', '', 'clerc', '', '');
INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('44', 'Baudouin de Cond\1\1', '', '', '', '', '');
INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('49', 'Brykhulle', '', '', '', '', '');
INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('50', 'Jean de Cond\1\1', '', '', '', '', '');
INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('51', 'Renaud d''Andon', '', '', '', '', '');
INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('52', 'Huon le Roi de Cambrai', '', '', '', '', '');
INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('53', 'Jean Castel (fils)', '', '1476', 'clerc', '', '');
INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('54', 'Thomas Maillet', '', '', '', '', '');
INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('55', 'Gautier de Coinci', '', '', 'moine', '', '');
INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('56', 'Robert Sainceriax', '', '', '', '', '');
INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('57', 'Philippe de Novare', '', '1264', '', '', '');
INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('58', 'Huon de Saint-Quentin', '', '', '', '', '');
INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('59', 'Jean Brisebarre', '', '', '', '', '');
INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('60', 'Henri de Valenciennes', '', '', '', '', '');
INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('61', 'Jean Le Petit', '', '', 'clerc', '', '');
INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('62', 'Jean Froissart', '', '', '', '', '');
INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('63', 'Guillaume d''Amiens le Peintre', '', '', 'bourgeois', '', '');
INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('64', 'Hoccleve', '', '', '', '', '');
INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('65', 'Andr\1\1 de Coutances', '', '', '', '', '');
INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('66', '\1\1tienne de Foug\1\1res', '', '', 'clerc', '1157', '1178');
INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('67', 'Jean (?)', '', '', '', '', '');
INSERT INTO "auteurok" ("a_index", "auteur", "born", "dead", "soc_status", "active_from", "active_to") VALUES ('68', 'Gieffroy', '', '', '', '', '');
