INSERT INTO "kapcsolatok" ("k_index", "m_index", "egyeb", "tipus", "v_index") VALUES ('11', '-1', '"Legenda de santo Stady" du v\1\1nitien Franceschino Grioni', 'mod\1\1le de', '108');
INSERT INTO "kapcsolatok" ("k_index", "m_index", "egyeb", "tipus", "v_index") VALUES ('5', '29', '', 'masik', '53');
INSERT INTO "kapcsolatok" ("k_index", "m_index", "egyeb", "tipus", "v_index") VALUES ('8', '62', '', 'certaines strophes de ce po\1\1me int\1\1gr\1\1 dans le manuscrit BNF fr. 763 du Dit du Cors.', '71');
INSERT INTO "kapcsolatok" ("k_index", "m_index", "egyeb", "tipus", "v_index") VALUES ('14', '29', '', 'masik', '126');
INSERT INTO "kapcsolatok" ("k_index", "m_index", "egyeb", "tipus", "v_index") VALUES ('13', '-1', 'Partage 11 strophes (10 \1\1 20 avec &#34Amour ne crient mort ne tourment&#34 qui a encore 4 strophes suppl\1\1mentaires \1\1 la fin du texte.', 'Partage 11 strophes (10 \1\1 20 avec &#34Amour ne crient mort ne tourment&#34 qui a encore 4 strophes suppl\1\1mentaires \1\1 la fin du texte.', '95');
INSERT INTO "kapcsolatok" ("k_index", "m_index", "egyeb", "tipus", "v_index") VALUES ('15', '-1', 'Ave maris stella', 'citations glos\1\1es', '128');
INSERT INTO "kapcsolatok" ("k_index", "m_index", "egyeb", "tipus", "v_index") VALUES ('16', '26', 'asd', 'dasd', '131');
INSERT INTO "kapcsolatok" ("k_index", "m_index", "egyeb", "tipus", "v_index") VALUES ('18', '-1', 'Poeme ins\1\1r\1\1 dans la piece de th\1\1atre Miracle de Th\1\1ophile dans le manuscrit BNF fr. 837', 'partie-tout', '197');
INSERT INTO "kapcsolatok" ("k_index", "m_index", "egyeb", "tipus", "v_index") VALUES ('19', '-1', 'Po\1\1me ins\1\1r\1\1 dans le Miracle de Th\1\1ophile', 'partie-tout', '198');
INSERT INTO "kapcsolatok" ("k_index", "m_index", "egyeb", "tipus", "v_index") VALUES ('17', '-1', 'Poeme ins\1\1r\1\1 dans la piece de th\1\1atre Miracle de Th\1\1ophile dans le manuscrit BNF fr. 837', 'partie-tout', '196');
INSERT INTO "kapcsolatok" ("k_index", "m_index", "egyeb", "tipus", "v_index") VALUES ('20', '-1', 'Po\1\1me ins\1\1r\1\1 dans le Miracle de Th\1\1ophile', 'partie-tout', '199');
INSERT INTO "kapcsolatok" ("k_index", "m_index", "egyeb", "tipus", "v_index") VALUES ('21', '-1', 'Traduction d''une \1\1l\1\1gie h\1\1bra\1\1que contenu dans le m\1\1me manuscrit.', 'traduction', '211');
INSERT INTO "kapcsolatok" ("k_index", "m_index", "egyeb", "tipus", "v_index") VALUES ('22', '171', '', 'm\1\1me motif (Pierre de la Broce)', '214');
INSERT INTO "kapcsolatok" ("k_index", "m_index", "egyeb", "tipus", "v_index") VALUES ('23', '22', '', 'Imitation de', '167');
INSERT INTO "kapcsolatok" ("k_index", "m_index", "egyeb", "tipus", "v_index") VALUES ('7', '-1', 'Vers de droit de Baudouin de Cond\1\1', '', '65');
INSERT INTO "kapcsolatok" ("k_index", "m_index", "egyeb", "tipus", "v_index") VALUES ('27', '-1', 'Avec V\1\1nus la d\1\1esse d''amour (fait partie du r\1\1pertoire)', 'strophes communes', '258');
INSERT INTO "kapcsolatok" ("k_index", "m_index", "egyeb", "tipus", "v_index") VALUES ('28', '-1', 'une source de V\1\1nus la d\1\1esse d''amour', 'source de', '258');
INSERT INTO "kapcsolatok" ("k_index", "m_index", "egyeb", "tipus", "v_index") VALUES ('30', '-1', 'Psaume LXXXIV', 'Paraphrase', '288');
INSERT INTO "kapcsolatok" ("k_index", "m_index", "egyeb", "tipus", "v_index") VALUES ('32', '-1', 'Pater Noster', 'Paraphrase', '291');
INSERT INTO "kapcsolatok" ("k_index", "m_index", "egyeb", "tipus", "v_index") VALUES ('33', '241', '', 'r\1\1futation de', '309');
INSERT INTO "kapcsolatok" ("k_index", "m_index", "egyeb", "tipus", "v_index") VALUES ('34', '-1', 'Pater noster', 'pri\1\1re glos\1\1e', '310');
INSERT INTO "kapcsolatok" ("k_index", "m_index", "egyeb", "tipus", "v_index") VALUES ('35', '-1', 'Credo', 'pri\1\1re glos\1\1e', '311');
INSERT INTO "kapcsolatok" ("k_index", "m_index", "egyeb", "tipus", "v_index") VALUES ('36', '244', '', 'citation, imitation de, r\1\1f\1\1rence a', '312');
INSERT INTO "kapcsolatok" ("k_index", "m_index", "egyeb", "tipus", "v_index") VALUES ('38', '-1', 'chansons courtoises diverses', 'refrains repris', '158');
INSERT INTO "kapcsolatok" ("k_index", "m_index", "egyeb", "tipus", "v_index") VALUES ('39', '-1', 'P\1\1lerinage de la vie humaine', 'insertion dans un texte', '318');
INSERT INTO "kapcsolatok" ("k_index", "m_index", "egyeb", "tipus", "v_index") VALUES ('31', '-1', 'Psaume LXXXIV', 'Paraphrase', '289');
INSERT INTO "kapcsolatok" ("k_index", "m_index", "egyeb", "tipus", "v_index") VALUES ('41', '58', '', 'strophes communes', '337');
INSERT INTO "kapcsolatok" ("k_index", "m_index", "egyeb", "tipus", "v_index") VALUES ('42', '-1', 'Lai de Kahedin (Roman de Tristan en prose)', 'r\1\1\1\1criture', '154');
INSERT INTO "kapcsolatok" ("k_index", "m_index", "egyeb", "tipus", "v_index") VALUES ('43', '-1', 'Salve Regina', 'priere glos\1\1e', '342');
INSERT INTO "kapcsolatok" ("k_index", "m_index", "egyeb", "tipus", "v_index") VALUES ('44', '209', '', 'imitation, reprise de vocabulaire', '345');
INSERT INTO "kapcsolatok" ("k_index", "m_index", "egyeb", "tipus", "v_index") VALUES ('45', '76', 'Des 15 strophes 11 se trouvent dans &#34Sav\1\1s...&#34', 'strophes communes', '96');
INSERT INTO "kapcsolatok" ("k_index", "m_index", "egyeb", "tipus", "v_index") VALUES ('46', '-1', 'Ave Maria en latin', 'priere glos\1\1e', '353');
INSERT INTO "kapcsolatok" ("k_index", "m_index", "egyeb", "tipus", "v_index") VALUES ('40', '264', '', 'partie du texte', '148');
INSERT INTO "kapcsolatok" ("k_index", "m_index", "egyeb", "tipus", "v_index") VALUES ('49', '-1', 'Facetus de Jean de Garlande', 'traduction de', '381');
INSERT INTO "kapcsolatok" ("k_index", "m_index", "egyeb", "tipus", "v_index") VALUES ('50', '-1', 'Facet latin anonyme en distique', 'traduction de', '382');
INSERT INTO "kapcsolatok" ("k_index", "m_index", "egyeb", "tipus", "v_index") VALUES ('51', '-1', 'Facet latin en hexam\1\1tres', 'traduction de', '388');
INSERT INTO "kapcsolatok" ("k_index", "m_index", "egyeb", "tipus", "v_index") VALUES ('47', '-1', 'Facetus de Jean de Garlande', 'traduction de', '378');
INSERT INTO "kapcsolatok" ("k_index", "m_index", "egyeb", "tipus", "v_index") VALUES ('52', '-1', 'source des refrains non-identifi\1\1e', 'citations de refrains', '373');
INSERT INTO "kapcsolatok" ("k_index", "m_index", "egyeb", "tipus", "v_index") VALUES ('53', '315', '', 'entit\1\1 enclose (pr\1\1c\1\1d\1\1 d''un prologue)', '402');
INSERT INTO "kapcsolatok" ("k_index", "m_index", "egyeb", "tipus", "v_index") VALUES ('54', '-1', 'Ave Maria', 'pri\1\1re glos\1\1e', '402');
INSERT INTO "kapcsolatok" ("k_index", "m_index", "egyeb", "tipus", "v_index") VALUES ('55', '-1', 'Ave Maria', 'pri\1\1re glos\1\1e', '403');
INSERT INTO "kapcsolatok" ("k_index", "m_index", "egyeb", "tipus", "v_index") VALUES ('57', '-1', 'du Facet de Jean de Garlande', 'traduction', '423');
INSERT INTO "kapcsolatok" ("k_index", "m_index", "egyeb", "tipus", "v_index") VALUES ('37', '-1', 'Benedicite dominus', 'priere glos\1\1e', '313');
INSERT INTO "kapcsolatok" ("k_index", "m_index", "egyeb", "tipus", "v_index") VALUES ('58', '-1', 'Les quatre \1\1ge de l''homme', 'insertion', '427');
INSERT INTO "kapcsolatok" ("k_index", "m_index", "egyeb", "tipus", "v_index") VALUES ('25', '-1', 'Avec V\1\1nus la d\1\1esse d''amour (fait partie du r\1\1pertoire)', 'strophes communes', '256');
INSERT INTO "kapcsolatok" ("k_index", "m_index", "egyeb", "tipus", "v_index") VALUES ('26', '-1', 'une source de V\1\1nus la d\1\1esse d''amour', 'source de', '256');
INSERT INTO "kapcsolatok" ("k_index", "m_index", "egyeb", "tipus", "v_index") VALUES ('59', '280', '', 'strophes communes', '450');
INSERT INTO "kapcsolatok" ("k_index", "m_index", "egyeb", "tipus", "v_index") VALUES ('60', '33', '', 'imitation m\1\1trique et th\1\1matique', '454');
INSERT INTO "kapcsolatok" ("k_index", "m_index", "egyeb", "tipus", "v_index") VALUES ('61', '-1', 'Roman de Fortune et de F\1\1licit\1\1', 'insertion', '456');
INSERT INTO "kapcsolatok" ("k_index", "m_index", "egyeb", "tipus", "v_index") VALUES ('62', '-1', 'Ave Maria', 'pri\1\1re glos\1\1e', '458');
INSERT INTO "kapcsolatok" ("k_index", "m_index", "egyeb", "tipus", "v_index") VALUES ('63', '-1', 'Salutation ang\1\1lique', 'variation', '278');
INSERT INTO "kapcsolatok" ("k_index", "m_index", "egyeb", "tipus", "v_index") VALUES ('64', '-1', 'Neuf Joies de la Vierge', 'paraphrase', '465');
INSERT INTO "kapcsolatok" ("k_index", "m_index", "egyeb", "tipus", "v_index") VALUES ('29', '224', '', 'Incipit variante', '280');
INSERT INTO "kapcsolatok" ("k_index", "m_index", "egyeb", "tipus", "v_index") VALUES ('24', '177', '', 'strophes communes', '252');
INSERT INTO "kapcsolatok" ("k_index", "m_index", "egyeb", "tipus", "v_index") VALUES ('12', '-1', 'Char d''orgueil', 'R\1\1f\1\1rence \1\1 un autre texte du meme auteur', '110');
INSERT INTO "kapcsolatok" ("k_index", "m_index", "egyeb", "tipus", "v_index") VALUES ('65', '-1', 'traduction de l''hymne latin Sanctitatis tocius femina qui se trouve dans le m\1\1me manuscrit, dans un \1\1tat fragmentaire: ses strophes alternent avec les strophes fran\1\1aises. Le po\1\1me latin est en d\1\1casyllabes.', 'traduction exacte', '470');
INSERT INTO "kapcsolatok" ("k_index", "m_index", "egyeb", "tipus", "v_index") VALUES ('66', '171', '', 'sujet identique', '479');
INSERT INTO "kapcsolatok" ("k_index", "m_index", "egyeb", "tipus", "v_index") VALUES ('67', '-1', 'Gilote et Johane (texte \1\1dit\1\1 par Jubinal dant Nouv. rec. II, 28-39.)', 'sujet identique', '486');
INSERT INTO "kapcsolatok" ("k_index", "m_index", "egyeb", "tipus", "v_index") VALUES ('56', '-1', 'Des proverbes latins sont glos\1\1s par des s\1\1quences de strophes en fran\1\1ais', 'proverbes glos\1\1s', '245');
