CREATE TABLE "manuscrit" (
    "manuscrit_id" integer NOT NULL DEFAULT nextval('manuscrit_manuscrit_id_seq'::text::regclass),
    "i_manuscrit" character varying(200),
    "i_datation10_1" character varying(100),
    "i_datation10_2" character varying(100),
    "s_datation10" character varying(100),
    "m_contexte9" character varying(100),
    "i_contexte90" character varying(200),
    "i_contexte91" character varying(200),
    "i_contexte92" character varying(200),
    "i_contexte93" character varying(200),
    "i_contexte94" character varying(200),
    "i_contexte95" character varying(200),
    "i_contexte96" character varying(200),
    "i_contexte97" character varying(200),
    "i_contexte98" character varying(200),
    "i_contexte99" character varying(200),
    "s_contexte1" character varying(100),
    "s_contexte2" character varying(100)
);
