INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('14', '3', 'harom', '2', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('158', '19', '10aaa', '108', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('54', '5', '8aaaa', '72', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('55', '11', '8aaaa', '72', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('56', '17', '8aaaa', '72', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('57', '28', '8aaaa', '72', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('58', '32', '8aaaa', '72', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('59', '45', '8aaaa', '72', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('68', '34', '12aaaaaaaaaaaa', '77', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('69', '42', '12aaaaaaaaaaa', '77', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('29', '7', '8aabaabbbaba', '36', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('38', '7', '12aaaaa (une initiale commence cette strophe, mais la premiere rime s''attache encore a la strophe pr\1\1c\1\1dente, contrairement aux quatre autres)', '49', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('70', '72', '12aaaaaaaaa', '77', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('36', '99', '12aaaaa', '47', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('71', '81', '12aaaaaaaaa', '77', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('204', '1', 'egy', '126', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('205', '2', 'ketto', '126', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('72', '84', '12aaaaaaaaaaa', '77', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('73', '92', '12aaaaaaaaa', '77', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('39', '90', '12aaaaa', '49', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('33', '2', 'ketto', '41', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('34', '3', 'harom', '41', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('207', '52', '12aaaaaa', '135', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('210', '1', '12aa', '137', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('45', '8', '12aa', '51', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('46', '10', '12aaa', '51', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('47', '16', '12aaa', '51', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('48', '22', '12aaa', '51', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('49', '28', '12aa', '51', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('40', '8', '12aa', '50', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('41', '10', '12aaa', '50', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('42', '16', '12aaa', '50', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('43', '22', '12aaa', '50', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('44', '28', '12aa', '50', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('211', '2', '12aa', '137', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('213', '19', '12aaa', '140', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('214', '20', '12aaa', '140', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('74', '97', '12aaaaaaaaa', '77', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('75', '103', '12aaaaaaaaa', '77', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('76', '105', '12aaaaaaaaa', '77', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('77', '116', '12aaaaaaaaa', '77', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('30', '2', '8aaaabbbabba', '39', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('31', '7', '8aabaabbabba', '39', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('78', '117', '12aaaaaaaaa', '77', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('79', '125', '12aaaaaaaaaaa', '77', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('141', '181', '12abb', '85', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('80', '14', '12aaaaa', '81', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('81', '25', '12aaaaaaaa', '81', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('82', '26', '12aaaaaaaa', '81', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('83', '28', '12aaaaaaaa', '81', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('84', '31', '12aaaaaa', '81', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('85', '34', '12aaaaaa', '81', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('86', '38', '12aaaaaa', '81', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('87', '39', '12aaaaa', '81', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('88', '47', '12aaaaa', '81', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('89', '51', '12aaaaa', '81', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('90', '53', '12aaaaa', '81', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('91', '55', '12aaaaa', '81', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('92', '62', '12aaaaa', '81', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('93', '75', '12aaaaa', '81', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('94', '79', '12aaaaa', '81', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('95', '94', '12aaaaa', '81', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('96', '105', '12aaaaa', '81', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('97', '133', '12aaaaa', '81', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('98', '136', '12aaaaa', '81', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('99', '159', '12aaaaa', '81', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('100', '77', '12aaaaaa', '81', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('101', '88', '12aaaaaa', '81', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('102', '116', '12aaaaaa', '81', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('103', '127', '12aaaaaa', '81', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('104', '150', '12aaaaaa', '81', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('105', '156', '12aaaaaa', '81', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('106', '166', '12aaaaaa', '81', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('107', '167', '12aaaaaa', '81', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('108', '170', '12aaaaaa', '81', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('109', '179', '12aaaaaa', '81', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('110', '180', '12aaaaaa', '81', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('111', '182', '12aaaaaa', '81', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('112', '187', '12aaaaaa', '81', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('113', '189', '12aaaaaa', '81', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('114', '192', '12aaaaaa', '81', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('115', '212', '12aaaaaa', '81', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('116', '214', '12aaaaaa', '81', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('117', '215', '12aaaaaa', '81', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('118', '64', '12aaaaaaa', '81', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('119', '73', '12aaaaaaa', '81', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('120', '132', '12aaaaaaa', '81', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('121', '142', '12aaaaaaa', '81', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('122', '50', '12aaaaaaaa', '81', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('123', '82', '12aaaaaaaa', '81', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('124', '137', '12aaaaaaaa', '81', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('125', '151', '12aaaaaaaa', '81', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('126', '163', '12aaaaaaaa', '81', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('127', '164', '12aaaaaaaa', '81', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('128', '203', '12aaaaaaaa', '81', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('129', '213', '12aaaaaaaa', '81', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('130', '89', '12aaaaaaaaa', '81', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('131', '56', '12aaaaaaaaaa', '81', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('132', '80', '12aaaaaaaaaa', '81', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('133', '184', '12aaaaaaaaaa', '81', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('134', '190', '12aaaaaaaaaa', '81', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('135', '208', '12aaaaaaaaaa', '81', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('136', '46', '12aaaaaaaaaaaa', '81', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('137', '36', '12aaaaaaaaaaaaa', '81', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('138', '52', '12aaaaaaaaaaaaa', '81', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('139', '176', '12aaaaaaaaaaaaa', '81', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('140', '152', '12aaaaaaaaaaaaaaaaaaaa', '81', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('142', '174', '12abbb', '85', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('143', '191', '12abcc', '85', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('144', '8', '12aaaa8A9A', '97', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('145', '36', '12aaaa10B6A', '97', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('146', '125', '7a3a7b7a3a7b7a3a7b7a3a7b', '98', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('147', '138', '7a3a8b7a3a7b', '98', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('148', '139', '7a3a7b7a3a7b7a3a7b7a3a7b7a3a7b7a3a7b7a3a7b7a3a7b', '98', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('149', '111', '12aaa', '100', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('159', '31', '10aaaaa', '108', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('160', '32', '10aaaaaa', '108', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('161', '43', '10a', '108', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('162', '58', '10aa', '108', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('163', '153', '10a', '108', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('164', '165', '10aaa', '108', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('165', '175', '10aa', '108', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('166', '204', '10aaa', '108', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('167', '242', '10aa', '108', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('168', '243', '10aaa', '108', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('169', '251', '10aa', '108', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('170', '254', '10aa', '108', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('171', '263', '10aa', '108', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('172', '306', '10aaa', '108', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('173', '335', '10aaa', '108', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('174', '352', '10aaa', '108', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('175', '385', '10aaa', '108', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('179', '186', '10aaa', '111', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('180', '9', '12aaaaaaaaa', '112', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('181', '11', '12aaaaaaaaa', '112', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('182', '12', '12aaaaaaaaa', '112', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('183', '14', '12aaaaaaaaa', '112', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('184', '15', '12aaaaaaaa', '112', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('185', '19', '12aaaaaaaaa', '112', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('186', '22', '12aaaaaaaaa', '112', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('187', '23', '12aaaaaaaaa', '112', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('188', '27', '12aaaaaaaaa', '112', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('189', '32', '12aaaaaaaaa', '112', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('190', '33', '12aaaaaaaaa', '112', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('191', '37', '12aaaaaaaaa', '112', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('192', '41', '12aaaaaa', '112', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('193', '48', '12aaaaaaaa', '112', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('194', '51', '12aaaaaaaaa', '112', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('195', '60', '12aaaaaaaaa', '112', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('196', '63', '12aaaaaaaaa', '112', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('50', '1', 'egy', '53', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('66', '46', '4a', '75', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('60', '12', '8aa4b', '73', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('61', '125', '8aa4b', '73', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('62', '141', '8aa4b', '73', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('63', '146', '8aa4b', '73', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('64', '159', '8aa4b', '73', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('65', '160', '8aa4b', '73', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('51', '2', 'ketto', '53', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('199', '4', '12aaa', '123', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('200', '7', '12aaaaa', '123', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('37', '8', '?', '48', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('208', '36', '12aaa', '136', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('209', '31', '12aaa', '136', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('212', '29', '12aaa', '138', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('215', '189', '12aa', '144', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('216', '2', '8aa7b8aa7b', '146', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('217', '3', '8aa7b8aa7b', '146', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('218', '4', '8aa7b8aa7b', '146', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('219', '9', '8aa7b8aa7b', '146', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('220', '13', '8aa7b8aa7b', '146', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('221', '14', '8aa7b8aa7b', '146', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('222', '15', '8aa7b8aa7b', '146', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('223', '16', '8aa7b8aa7b', '146', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('206', '1', 'asdsad', '131', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('225', '20', '12aaa', '179', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('226', '2', '7abbaabaaba', '192', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('227', '2', '7abbaabaaba', '193', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('35', '74', '12aa', '46', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('228', '7', '12aaa', '228', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('230', '9', 'aabccdeed', '231', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('231', '4', '6abababcb', '232', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('232', '10', '6abababcb', '232', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('233', '11', '6ababcbcb', '232', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('236', '30', 'aab', '240', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('237', '31', 'a', '240', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('238', '17', '8aabaabbbbbba', '241', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('239', '5', '12aaa', '246', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('240', '48', '12aaa', '246', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('241', '53', '12aaa', '246', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('242', '54', '12aa', '246', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('243', '83', '12aaa', '246', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('244', '114', '12aaa', '246', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('245', '107', '12xaaa', '246', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('224', '8', '10aabb', '153', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('234', '3', '12aaaaa', '235', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('235', '46', '12aaaaa', '235', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('229', '16', 'aabaab', '229', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('274', '9', '8abab', '292', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('259', '1', '8aabbccddeeff', '262', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('260', '10', '8aabbccddeeff', '262', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('261', '11', '8aabbccddeeff', '262', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('262', '12', '8aabbccddeeff', '262', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('263', '13', '8aabbccddeeff', '262', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('264', '14', '8aabbccddeeff', '262', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('267', '1', '(onze vers)', '274', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('277', '24', '8ababab', '300', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('278', '22', '8ababab', '303', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('280', '1', '8aabb', '331', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('281', '166', '12aaab', '332', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('282', '2', '8aaa', '154', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('283', '5', '8aa', '154', NULL);
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('26', '7', '12aaa', '35', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('27', '14', '12aaa', '35', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('28', '17', '12aaa', '35', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('284', '1', '8aa4b8cc4b', '152', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('285', '4', '12aaaaAA', '366', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('286', '7', '12aaaaBA', '366', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('287', '8', '12aaaaAA', '366', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('288', '11', '12aaaaAA', '366', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('16', '38', '12aaaa8B6A', '26', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('17', '39', '12aaaa8B8A', '26', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('18', '42', '12aaaa6A5B5A', '26', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('19', '44', '12aaaa6B6A', '26', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('20', '94', '7ababbab', '26', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('21', '95', '7ababbab', '26', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('22', '96', '7ababbab', '26', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('23', '97', '7ababbab', '26', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('24', '98', '7ababbab', '26', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('25', '99', '7aba', '26', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('290', '44', '8aabbcc', '379', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('291', '48', '8aa', '379', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('292', '51', '8aa', '379', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('293', '54', '8aa', '379', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('294', '22', '12aaaaaa', '385', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('295', '30', '12aaaaaa', '385', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('296', '34', '12aaa', '385', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('201', '10', '12aaaaa', '125', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('202', '15', '12aaaaa', '125', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('203', '18', '12aaaaa', '125', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('156', '1', '5aabaab', '105', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('150', '3', '5abcabc', '105', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('151', '9', '5aab', '105', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('157', '13', '5aabaab', '105', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('275', '11', '12aaaa', '296', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('276', '12', '12aaaa', '296', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('297', '4', '10aabcaaaccccaccca', '392', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('298', '1', '12aaaa', '395', '1');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('299', '9', '12aaaa', '395', '1');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('289', '1', '12aaaaa', '369', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('300', '1', '12aaaa', '401', '1');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('302', '1', '8aabbccd7D5D', '424', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('303', '1', '12aaab', '445', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('304', '2', '12aaaa', '445', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('305', '18', '12aabbb', '445', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('306', '22', '12aa', '445', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('307', '32', '12aaaaaa', '445', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('308', '37', '12aa', '445', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('309', '44', '12aa', '445', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('310', '52', '12aabbbb', '445', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('311', '2', '12aaaaaa', '449', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('15', '8', 'aaba', '21', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('312', '4', '8aabbccddeeff', '455', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('67', '105', '8aa4b', '76', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('313', '1', '12aaaa', '458', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('314', '3', '12aaaaa', '461', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('279', '2', '12aabb', '319', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('154', '1', '5aabaab', '106', '1');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('152', '3', '5aabaab', '106', '1');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('155', '13', '5aabaab', '106', '1');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('246', '7', 'aabaabaab', '253', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('247', '17', 'aabaaab', '253', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('53', '3', '12aaaaa', '64', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('248', '4', '12aabb', '259', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('249', '5', '12aabb', '259', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('251', '7', '12aabb', '259', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('252', '8', '12aabb', '259', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('253', '9', '12aabb', '259', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('250', '12', '12aabb', '259', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('254', '13', '12aabb', '259', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('255', '14', '12aabb', '259', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('256', '15', '12aaa2b', '259', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('257', '4', '8ababcdcd', '260', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('258', '5', '8ababcadadc', '260', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('268', '3', 'abcaddcddc', '278', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('269', '4', 'ababaacaac', '278', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('270', '5', 'ababaacaac', '278', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('271', '6', 'ababccdccd', '278', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('272', '7', 'ababccdccd', '278', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('315', '8', 'ababccdccd', '278', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('316', '9', 'ababccdccd', '278', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('317', '10', 'ababccdeed', '278', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('318', '11', 'ababccdccd', '278', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('176', '6', '8aa4b8cc4b', '110', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('177', '19', '8aa4b8cc4b (a et c sont les memes rimes, mais a masculine, c f\1\1minine)', '110', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('178', '37', '8aa4b8cc4b (a et c sont les memes rimes, mais a masculine, c f\1\1minine)', '110', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('197', '86', '8aaa', '114', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('198', '94', '8aaa', '114', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('52', '26', '12aaa', '62', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('319', '14', 'ababababab', '477', ' ');
INSERT INTO "strofak" ("s_index", "s_szam", "s_ertek", "v_index", "c_szandekos") VALUES ('320', '1', '12aaaaaa', '483', ' ');
