INSERT INTO "versek" ("m_index", "incipit") VALUES ('70', 'El non de Jesu Crist, qui est nostre douz pere');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('2', 'Ave en cui sans nul nombre a');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('13', 'Devotte dame qui contemplez les faitz');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('14', 'Jhesus divine sapience');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('15', 'Je ne sai dou monde que dire');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('16', 'Royne de piti\1\1 Marie');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('17', 'Ave dame des angres de paradis royne');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('18', 'Dieus te saut estoile de mer');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('19', 'Dieu ait l''ame des trespassez');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('20', 'O glorieuse trinit\1\1');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('21', 'Ave Maria o tres douce Marie');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('22', 'Miserere mei deus');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('24', 'J''estoie l''autre jour en contemplation');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('25', 'Ave glorieuse pucele');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('26', 'Ave royne glorieuse');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('27', 'Qui d\1\1\1amours vueult ouyr cy s\1\1\1aprochoit avant');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('28', 'Amour, amour, ou estes vous');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('30', 'L\1\1\1autrier par un matin esbanoiant aloie');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('31', 'Cil qui son sens ne met a oevre');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('32', 'Bonne gent, entendez par amours .j. biau dit');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('33', 'Amours qui m''as mis en soufranche');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('35', 'Amours, j''ai o\1\1 de vous faire');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('36', 'Puis que m''entente ay mise en nouviau dit retrere');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('37', 'Uns livres est escript, or oez qu''il y a');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('100', 'Pour recorder un dit sui orendroit venus');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('39', 'Porte de para\1\1s, espoir de pecheor');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('94', 'Vous qui vol\1\1z o\1\1r, retenir et aprendre');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('41', 'En l''onneur de la droituriere');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('48', 'Seigneurs, j''ay o\1\1 dire souvent en aucuns lieux');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('45', 'Le roy de paradis''');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('49', 'La Vierge glorieuse, qui le doulx Dieu porta');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('50', 'A Romme eut un bourgois qui estoit de grant prix');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('56', 'Ici comence li romanz des romanz');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('51', 'Jhesus Crist qui pour nous he\1\1t persecucion');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('52', 'A la digne lo\1\1nge du pere glor\1\1eux');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('53', 'Dieu, qui est sans fin et sans commencement');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('54', 'Devant l''uis au riche homme le ladre s''aresta');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('46', 'Le roy de paradis qui pour nous c''estendy');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('57', 'Re\1\1ne corounee, flur de Para\1\1s');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('58', 'Or entendez une complainte');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('60', 'Diex qui por nous sauver voult en terre descendre');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('61', 'Puis que blasm\1\1s sui et mesdis');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('62', 'Cors, en toi n''a point de savoir');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('63', 'Piti\1\1s de moi premierement');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('64', 'Deu vous dorra grant honour');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('65', 'Nove chan\1\1on vos dimes de bele antiquit\1\1');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('66', 'Douce gent, je vous prie que vous vous veilliez taire');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('67', 'L''auctorit\1\1 nos dit une raison por voir');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('68', 'A la Deu loenge e a la sue gloire');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('69', 'Les seignors anciains qui ont batailleor');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('10', 'Glorieuse Vierge roine');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('71', 'Jhesucrist qui sur touz est vray fusicien');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('72', 'Pius Dieus, de cui tous biens doit muevre');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('73', 'Encor ne soit loenge de pecheour pas bele');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('74', 'Douls Jhesucris, je vieng a vous');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('75', 'Pour moustrer que dieus s''esbanie');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('76', 'Sav\1\1s que j''apiel Beghinage?');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('77', 'Amour ne crient mort ne tourment');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('78', 'Miracles sont d''amours: trop me font merveillier');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('79', 'Pour ce que de mal faire ne puet nul bien venir');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('80', 'Filz de Dieu paint en crucefi');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('81', 'Dites vos patenostres pour toute sainte \1\1glise');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('82', 'Femmes a la pie');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('83', 'Or escoutez, seignor, et si ne vous anoie');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('84', 'Seignor et dames, entendez tuit a moi');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('85', 'De bone femme la bount\1\1');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('86', 'Qui bien velt commenchier a parler');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('87', 'D''une france pucele vos vuel dire et conter');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('88', 'En la douce loange de la Vierge pucelle');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('89', 'Reis Arflet de Nohundrelande');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('90', 'En le douche saison jolie');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('91', 'Par la grace de Dieu, nostre souverain pere');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('92', 'Moult fu nez de bone heure qui bien fait en sa vie');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('93', 'A totes bones gens qui ont entendement');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('40', 'Pour ceulz qui se desroient trop outrageusement');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('95', 'Mout a entre triacle et venin grant discorde');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('96', 'Qui en bel rimer velt entendre');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('97', 'Oiez une ten\1\1on qui fu fete pie\1\1a');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('98', 'Au tans anciennor, ice vous di pour voir');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('38', '(Cy) Voulez o\1\1r un petit compte');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('99', 'Roy des roys, Dieux des dieus, qui de ta deitez');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('101', 'Un homme avoit est\1\1 hermite longuement');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('102', 'Glorieuse Vierge Marie');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('103', '[...] Empetre nous au tres haut sire');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('104', 'Une grant vision est en ce livre esripte');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('105', 'Ou principe erat verbum');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('108', 'L''Escripture tesmoingne et nous fait asavoir');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('109', 'Tuit cil soient benei de Dieu et de sa Mere');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('110', 'A la douce loenge de la Vierge Marie');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('111', 'A toutes bones gens ne devroit pas desplaire');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('112', 'Le dous Roys Jhesucris, qui par annuncion');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('113', 'Li dous Roys Jhesucris, qui par annuncion');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('114', 'Tous ceulz qui volentiers oient de Dieu parler');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('115', 'Moult est bone acointance d''estoire, bone gent');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('116', 'Toutes bones gens doivent oyr le bien retraire');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('117', 'Tu qui as en pechi\1\1 vescu tout ton aage');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('118', 'Seigneur, je di pour voir, qui a entendement');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('119', 'Puis que Diex m''a prest\1\1 sens et entendement');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('120', 'Dieu et sa douce mere, que chascun doit amer');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('121', 'Pour donner par exemple prouesce et hardement');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('122', 'Touz ceus et toutes celles qui croiront fermement');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('123', 'Au temps qu''en crois li Fil pendoit');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('125', 'A ces festes et as haus jours');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('126', 'A ces hautes solempnit\1\1s');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('127', 'A droit me plaings qui suis Rome nomm\1\1e');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('128', 'Ains iroie trans maria');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('129', 'A la fois avient que li home');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('130', 'Al Deu loenge en son service');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('131', 'A matines voleit Jhesu orer');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('132', 'Amours, a vous ainz qu\1\1\1a nului');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('133', 'Amours est vie glorieuse');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('134', 'Amours gist en maladie, charit\1\1 est nafr\1\1e');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('135', 'Amours qui m\1\1\1a en sa justise');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('136', 'Aprenez a mengier joute');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('137', 'Assez avez \1\1y et contes et fabliaus');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('138', 'Ave dame des anges, ave royal Marie');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('139', 'Ave dame, je vos salu');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('140', 'Ave qui ainz ne commenchas');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('141', 'Ave Sainte Marie de grant misericorde');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('142', 'Beau seigneur et vos dames, faites que l''en vous oye');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('143', 'Benedicite dominus');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('144', 'Biaus sires Dieus, que vaut, que vaut');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('145', 'Bien deussons essample prendre');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('146', 'Bien est amez qui amors aimme');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('147', 'Bien et Mal unt fet covenant');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('148', 'Bon fait regner en nette guise');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('149', 'Bonnes gens, je puis tesmoignier');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('150', 'En nom de Dieu l''esperit\1\1');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('151', 'Laissier m''estuet le rimoier');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('152', 'Seignor, or escoutez, que Diex vos soit amis');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('153', 'Iriez, a maudire la mort');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('154', 'Rimeir m''estuet d''une descorde');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('155', 'Rimer m''estuet, c''or ai matire');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('156', 'Ribaut, or estes vos a point');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('157', 'Signour, moult me merveil que ciz siecles devient');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('158', 'En riens que Beguine die');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('159', 'Sopirant pour l''umain linage');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('160', 'H\1\1 laz, chetis, dolenz, que porrai devenir');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('161', 'Sainte ro\1\1ne bele');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('162', 'L''autrier un jor joer aloie');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('163', 'Cil Damediex qui fist air, feu et terre et meir');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('164', 'La mors, qui toz jors ceulz aproie');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('165', 'De corrouz et d''anui, de pleur et de piti\1\1');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('166', 'L''autrier entour la Saint Remei');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('167', 'Tant ai par maintes foy parl\1\1 de vanit\1\1');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('168', 'Seignor, or fetes pais, daigniez un poi entendre');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('169', 'Mont sont il a meschief mis l''esgar\1\1e gent');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('170', 'Grant douleur me contraint de faire ma complainte');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('171', 'Heu, heu, michi, las chetif, domine');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('172', 'Seignor, or escoutez, li grant e li menor');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('173', 'Ave Jhesu ki pur nus pecheurs del cel descendistes');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('174', 'Catun esteit paiien');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('175', 'Gloriuse reine, heiez de mei merci');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('176', 'Marie, pur toun enfaunt');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('177', 'Un rois jadis estait qe avait un amye');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('178', 'Le Seint Espirit');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('179', 'De un chemin plus large assetz');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('180', 'Doctriner doit les autres cui Diex science done');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('181', 'Por le monde qui est nuit et jor en discorde');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('182', 'L''en dit que tout au tens huche cil a la porte');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('183', 'Seignor, j''ai folement mes deniers despenduz');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('184', 'Mon cuer si m''a don\1\1 matere');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('185', 'Que que li autre facent de parler ou de tere');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('186', 'Recorder voil la joie primere');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('187', 'Dame plesant et sage de touz biens doctrin\1\1e');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('188', 'Pater noster doit chascuns dire');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('189', 'Or m''estuet saluer');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('190', 'Douce dame, salut vous mande');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('191', 'Merveille est de ceste monde comme torne bouele');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('192', 'De celui haut seigneur qui en la croix fu mis');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('193', 'De lor menconges vuelent viure li mencongier');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('194', 'Femes sont de diverse vie');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('195', 'Du monde qui fet a reprendre');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('196', 'Conter me plaist une merveille');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('197', 'Tout auxi com par la fum\1\1e');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('198', 'Or vint la tens de may que ce ros panirra');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('199', 'Ce je ay dit dez fammes choze que leur enuit');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('200', 'Ces parolles aprent li saiges par un livre');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('201', 'Or entendez seigneurs, que Jhesus vous beneye');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('202', 'Tant voi le siecle bestourner');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('203', 'Pucelle graciouze, on main tout vrai honeur');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('204', 'Mon boen ami, Dieux le maintieingne');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('205', 'Puis que hom deit de ci partir');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('206', 'Seignours, ore escotez haute chivalerye');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('207', 'Le mel de ceel');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('208', 'Douz sire seint Franceis ke Jhesu tant amastes');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('209', 'Piti\1\1s o me matire puise');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('210', 'Ausi com vrais chimens joint deus quariax ensanble');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('211', 'A l''oure de meydi en la plus grant chalour');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('212', 'Ave tres gloriouse dame d''umiliteit');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('213', 'Ave virge gratiouse');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('214', 'Ave dame de cui volt naistre');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('215', 'Bonne gent, ouy\1\1s, je vous prie');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('216', 'Croix, je me vueil a toi complaindre');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('217', 'Douce dame, pie mere');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('218', 'Glorius rei, le fiz sainte Marie');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('219', 'He, plaine de grace divine');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('220', 'Je te salue, Maria');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('59', 'Mere Dieu, qui vous siert mout a bon guerredon');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('221', 'Marie mere douce Jesucrist');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('222', 'Jhesu, ma joie et mon repose');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('223', 'Dieu vous sauve Marie');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('224', 'Marie mere merciable');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('225', 'Merciable miere Marie');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('226', 'O precieus saint Marc evangelistes');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('227', 'Cil qui pour nous prist char humaine');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('228', 'Quant Dieu le monde composa');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('229', 'E tres noble vierge enterine');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('230', 'Par exemple vorai parler de l''Escripture');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('231', 'Pater noster, vrais peres, qui es sire dou monde');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('232', 'Peres, qui au ciel fais demeure');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('233', 'Quant Dieu ensemble maria');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('234', 'Sire, fiz Deu omnipotent');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('235', 'Virge chascuns scet vraiement');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('236', 'Sainte Marie, Dame, glorieuse puciele');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('238', 'Ce dist uns clers Plantefolie');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('239', 'Quiconques velt mener pure et saintisme vie ');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('240', 'Dieu gart la compaignie de pechiez et de crime');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('241', 'Chascun me dit a quoy je pance');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('242', 'Que Dieu me gart de mal et d''ire');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('243', 'Cil qu''estaublit Pierre l''apostre');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('244', 'Pater noster sens le Credo');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('245', 'Le grant Credo sens le petit');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('246', 'Seigneur, pour Dieu, paix facite');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('247', 'Pour eschevir mirancolie');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('248', 'Comment que men tans aie us\1\1');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('249', 'O digne preciosit\1\1');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('250', 'Mors, comment que je me deduise');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('251', 'A toi, du monde le refui');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('252', 'La reigne de pecch\1\1 est estreite de haut lignage');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('253', 'Bonne gent, l''autre jour dedans mon lit sonjoie');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('254', 'Merveille est que ne fenist');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('255', 'Dire me plaist et bien doit plaire');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('256', 'Oez dit de petit volume');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('257', '(...) La Virge put hore asener');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('258', 'Qi est la piere de Escoce, vous die pur verit\1\1');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('259', 'Glorious Sire Pere qui le mont racatas');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('260', 'Ore entendez la passiun');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('261', 'Pour chou que on tiesmoingne par tout generaument');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('262', 'Auchune gent m''ont fait proiiere');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('263', 'Pourtant, se j''ay la teste folle');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('264', 'Li sages nous moustre et descueure');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('265', 'Dit vous ai d''armes et d''amours');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('266', 'Drois m''ensengne que je doi dire');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('267', 'Li Peres et li Filz et li sains Esperis');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('268', 'Fortune, mere de tristece');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('269', 'Salve pucelle precieuse');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('270', 'Pour ce que aucuns desirent et ont fain de savoir');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('271', 'Se je savoie dire ou faire');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('272', 'Seynte Marie, pleyne de grace e de pi\1\1t\1\1');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('273', 'Ave sainte Marie, la mere al creatur');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('274', 'Sire Dieu Jhesucrist, mon salut et ma vie');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('275', 'Mors, si te s\1\1s entrebouter');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('276', 'En une pomme fu la mors');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('277', 'Ave vierge de parfait priz');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('278', 'L''autre jour mon chemin erroie');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('279', 'L''autrier m''en aloi juant');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('280', 'Qui voudroit l''art d''amors et savoir et aprendre');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('281', 'Ceus qui voudront oir un biau dit recorder');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('282', 'Seignor, voulez oir de patre decio');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('283', 'Jehans de Cond\1\1 nous raconte');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('284', 'Hons navrez a mestier de mire');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('285', '(...) por lui achoisoner');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('286', 'Jeo say un dame de bone purveaunce');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('287', 'Je maine bone vie semper quantum possum');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('288', 'Je crois en ung seul Dieu le Pere');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('289', 'Sainte Eglise se plaint, ce n''est mie merveille');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('290', 'Se li rois de Cambray veist');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('291', 'En l''oneur et a la loenge de Jhesu Crist premierement');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('292', 'Ave Jhesu, reis omnipotent, ki home peccheur eustes si chier');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('294', 'Del\1\1s la croix moult doloreuse');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('295', 'Gens, sans conseil et aussi sans prudence');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('296', 'Qui de translater s''entremet');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('297', 'N''est pas sire de son pa\1\1s');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('298', 'Tout homme desire scavoir');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('299', 'Chieulx qui voelt faitis devenir');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('300', 'Jhesucrist, dous amis, cum l\1\1\1ame aura bon tans');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('301', 'Ki aroit mis son cuer et desiriers lassus');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('302', 'Antandeis, bones gens, que Deus vous benoie');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('303', 'Cathon qui fu moult sages homs');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('304', 'Nuyl ne deit mounter en pris');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('305', 'Marie, dame toute belle');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('306', 'O tres glorieuse en toute precellence');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('307', 'Hugue Aubriot bien me recors');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('308', 'Mos sans vilonnie');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('309', 'Por mon cuer resbaudir et pour reconforter');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('310', 'E, douz cuers, douce amie, tres douce creature');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('311', 'Ribaus, par le pa\1\1s ser\1\1s');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('293', 'Bele, salus vous mande, mes ne dirai pas qui');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('312', 'Gemme resplendissanz, ro\1\1ne glor\1\1euse');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('313', 'Marie, mere de concorde');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('314', 'Dame de paradis, dame de tout le monde');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('315', 'A la fin de cest livre, ou j''ai pen\1\1 jour maint');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('316', 'Ave dame de gloire, ave dame des angeles');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('317', 'Ave dame tres souveraine');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('318', 'Biaus sires Jhesucris, mes salus et ma vie');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('319', 'Dame, pour ton biau fis que tu par amais tant');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('320', 'Biaus tres dous Jhesucris, je vos weul aorer');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('321', 'Eya ore ma duce amie');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('322', 'Li haus sires dou ciel nos doint ferme creance');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('323', 'Diex Sire, Pere poste\1\1s');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('324', 'Ave, le douce comencement');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('325', 'Elite amie Jhesucrist, seinte Katerine');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('326', 'O virge Katherine, de Deu perfaite amie');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('327', 'Tres debonnaire dame, eurouse pecheresse');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('330', 'han');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('331', 'Tres debonnaire dame, eurouse pecheresse');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('332', 'Saint Pierre, glorieux martir');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('237', 'O Saint Sebastien, martir tres precieus');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('333', 'Mon cuer, trise penssis me semont que je die');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('334', 'Cuard est qui amer n''ose');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('335', 'Signeur, pour Dieu servir par grand devotion');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('336', 'Mieulx vault assambler un tresor');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('337', 'Il avint l''autrier a Saint Gille');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('338', 'Apres vient une corte rime');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('124', 'Chius ki le cuer a irascu');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('29', 'Ceux qui puissans et riches a tousjours estre vuelent');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('339', 'Rome, Jherusalem se plaint');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('340', 'Oies de haute estore l''uevre');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('341', 'Dame plus douce que seraine');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('342', 'Mors, qui en tant de lieu s''espart');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('343', 'On dit que par commun usage');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('344', 'Pour venir de pechie au cor');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('345', 'Puis que jou trouver sai, bien doi tel cose dire');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('346', 'J''ai oy dire que jadis');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('347', '(...) On a les barons longuement');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('348', 'Seignour, cis siecles ne vaut rien');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('349', 'Quiconques met s''entencion');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('350', 'Seigneurs, je di pour voir, oians tous en apert');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('351', 'Ave dame, je te salu');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('352', 'Qu''encontre tous pechiez puisse avoir fort armee');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('353', 'Je me plaing de celui qui au celier converse');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('354', 'Une grant aventure tantost vous conteron');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('355', 'Se povret\1\1 estoit richesse');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('356', 'Je qui povres hons sui et qui n''ai que donner');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('357', 'Dame de grant deduit, ne me puis apenser');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('358', 'Pour le plaisir ma dame faire');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('359', 'Aucuns me scevent mauvais gre');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('360', 'Amours, mout as bele venue');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('361', 'Je ne sai par ou je coumance');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('362', 'Helaz com raison et lumiere');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('363', 'Deu ke est gelous de vertue e bountee');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('364', 'Deu ke est gelous de vertue e bountee');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('365', 'Reigne des aungles recevez cest ave');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('366', 'Ave virge Marie');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('367', 'Si cum jeo ju en un lit');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('368', 'Croiz sentyme honour\1\1e');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('369', 'Salemon feit un petit livre');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('370', 'O femme qui es plaine de toute saintet\1\1');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('371', 'Qui d''amors velt selonc son sens user');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('372', 'Oez, seignurs, pur Deu vus pri');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('373', 'Questionner vos veil d''un jugement');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('374', 'Jehan a dit et fet mainte rime nouvele');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('375', 'Ma volent\1\1 est bone et preste');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('376', '[...] Trop ai chier achat\1\1 l''avoir');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('377', 'Ens en l''onneur de Dieu le pere tout puissant');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('378', 'Rome du mont est chief, ainsi est apelee');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('379', 'Iver li pereceus, qui toz jors frit et tremble');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('380', 'Vous qui bien et honneur et les biaus dis amez');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('381', 'Se je vos fas entendre, si me dev\1\1s o\1\1r');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('382', 'As abb\1\1s, as noirs moines, as nonnains ensement');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('383', 'On dist que tous temps fait boin dou bien le bien dire');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('384', '');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('385', '');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('386', '');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('387', '');
INSERT INTO "versek" ("m_index", "incipit") VALUES ('388', '');
