INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('10', 'Thomas Walton: Notes sur le manuscrit 871 de la Biblioth\1\1que municipale de Grenoble, Romania 54 (1928), pp. 465-475.', 'Tanulm\1\1nyok');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('8', 'Jean Morawski: Les Miracles en quatrains alexandrins monorimes, Romania, 65 (1939)', 'Bibliogr\1\1fi\1\1k');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('11', 'Ilvonen, E.: Parodies de th\1\1mes pieux', 'Sz\1\1vegkiad\1\1sok');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('9', 'Wolfram Kleist: Die erz\1\1hlende Dit-Literatur in "quatrains alexandrins monorimes", Hamburg, Helmut Buske Verlag, 1977.', 'Sz\1\1vegkiad\1\1sok');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('12', 'Berhardt, A.: Die altfranz\1\1sische Helinandstrophe, M\1\1nster, 1912.', 'Tanulm\1\1nyok');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('13', 'Mourin, L.: Po\1\1sies religieuses fran\1\1aises inconnues, in Scriptorium 3 (1949) pp. 218-229.', 'Tanulm\1\1nyok');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('14', 'Reinsch, Robert: Mittheilungen aus einer franz. Handschrift des Lambeth Palace zu London, in Arhiv f\1\1r das Studium neueren Sprachen und Literaturen, 63.', 'Tanulm\1\1nyok');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('56', '. Nystr\1\1m: Po\1\1mes sur les biens d''un m\1\1nage, Annales Academiae Scientiarum Fennicae, B/46, Helsinki, 1940.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('51', 'La plainte d''amour. Poeme anglo-normand publi\1\1 pour la premiere fois par Johan Vising, G\1\1teborg, Wald. Zachrissons, 1905.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('53', 'Arthur Langfors, Le Mariage des sept arts par Jehan le Teinturier d''Arras suivi d''une version anonyme. Poemes francais du XIIIe siecle, Paris, Champion 1923.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('54', 'Arthur Langfors: Li Ave Maria en roumans par Huon le Roi de Cambrai', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('55', 'Jean Morawski: Les Miracles en quatrains alexandrins monorimes, Romania, 65 (1939)', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('57', 'Le roman des romans. An old french Poem, ed. Irville C. Lecompte, Princeton - Paris, 1923.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('58', 'F. J. Tanquerey: Plaintes de la Vierge en anglo-fran\1\1ais (XIIIe et XIVe si\1\1cles), Paris, Champion, 1921.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('59', 'Pierre Ruelle: Les dits du Clerc de Vaudoy, Bruxelles, Presses Universitaires de Bruxelles, 1969.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('60', 'Langfors, Arthur: Notice du manuscrit fran\1\1ais 9220 de la Biblioth\1\1que Nationale, Romania 54 (1928).', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('61', 'Schutz, A. H.: Le dit du cordouanier, Romanic Review, 22 (1931), 130-136.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('62', 'Arthur Langfors: Du Mesdisant par Perrin la Tour (Bibl. Nat. fr. 25462), ROmania 40, 1911, pp. 559-570.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('63', 'Karl Bartsch: La langue et la litt\1\1rature fran\1\1aises depuis le IXe jusqu''au XIVe si\1\1cle, Paris, 1887.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('65', 'Thomas Wright: Anecdota Literaria; A Collection of Short Poems in English, Latin, and French, London, J. R. Smith, 1844.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('66', 'La plainte d''''amour. Poeme anglo-normand publi\1\1 pour la premiere fois par Johan Vising, G\1\1teborg, Wald. Zachrissons, 1905.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('67', 'Raymond T. Hill: "La Vie de Sainte Euphrosine", Romanic Review, 10 (1919), pp. 159-169, 191-232.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('68', 'Werner S\1\1derhjelm: Une vie de saint Quentin en vers fran\1\1ais du Moyen Age, M\1\1moires de la Soci\1\1t\1\1 N\1\1o-philologique \1\1 Helsingfors, 3 (1902), pp. 443-525.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('69', 'Erik Westberg: La vie de saint Jean l''Evang\1\1liste. Po\1\1me religieux du XIIIe si\1\1cle, Uppsala, 1943.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('70', 'Karl Reichl: An Anglo-Norman Legend of Saint Margaret, Romania 96 (1975), pp. 53-66.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('71', 'Raymond T. Hill: Two Old French Poems on Saint Thibaut, New Haven, Yale University Press, 1936.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('72', 'Karl Breul: Le Dit de Robert le Diable, in Abhandlungen Herrn. Prof. Dr. Adolf Tobler zur Feier..., Halle, Max Niemeyer, 1895, 464-509. ', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('73', 'Hugues Micha: Une r\1\1daction en vers de la Vie de Saint S\1\1bastien, Romania 96 (1975), pp. 405-419.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('74', 'Louis Brandin: "La traduction fran\1\1aise des Sortes Apostolorum", Romania, 43 (1914), pp. 481-494.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('75', 'Tauno F. Mustanoja: Les neuf joies Nostre Dame, Annales Academiae Scientiarum Fennicae, Ser. B, Tome 73,4, Helsinki, 1952.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('79', 'Arthur Langfors: Notice du manuscrit fran\1\1ais 17068 de la Biblioth\1\1que Nationale, Romania 43 (1914).', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('76', 'Maurice Wilmotte: L''enseignement de la philologie romane \1\1 Paris et en Allemagne, Bruxelles, 1886.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('77', 'E. Bechmann: Drei dits de l''ame aus der Handschrift Ms. Gall. Oct. 28 der K\1\1niglichen Bibliothek zu Berlin, ZrPh 13, pp. 35-84.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('80', 'Jubinal: Contes, dits, fabliaux, moralit\1\1s et autres pi\1\1ces in\1\1dites des XIIIe, XIVe et XVe si\1\1cles...', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('81', 'Paul Meyer: Notices et extraits du ms. 8336 de la b\1\1blioth\1\1que de sir Thomas Phillipps, \1\1 Cheltenham, Romania, 13 (1884), 497-541.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('82', 'Philippe M\1\1nard: Le dit d''aventures, in: Etudes de langues et de litt\1\1rature du Moyen Age offertes \1\1 F\1\1lix Lecoy, Paris, Champion, 1973.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('83', 'A. C. Ott: "Das altfranz\1\1sische Eustachiusleben (L''estoire d''Eustachius) der Pariser Handschrift Nat.-Bibl. rf. 1374", Romanische Forschungen, 32, pp. 481-606.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('84', 'Denomy, Alexander Joseph: The Old French Lives of Saint Agnes and Other Vernacular Versions of the Middle Ages, Cambridge, Harvard University Press, 1938.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('85', 'Munk Olsen, B.: Dits en quatrains d''alexandrins monorimes de Jehan de Saint-Quentin, Paris, Soci\1\1t\1\1 des anciens textes francais, 1978.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('86', 'Holden, Anthony J.: Le Roman des Franceis, in: \1\1tudes de Langues et de Litt\1\1rature du Moyen Age offertes \1\1 F\1\1lix Lecoy, Paris, Champion, 1973, pp. 213-233.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('87', 'Scheler, August: Dits et contes de Baudouin et de son fils Jean de Cond\1\1, Bruxelles, Devaux, 1867 (vols. 1-3).', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('64', 'Arthur Langfors: Li despisemens du cors (Bibl. Nat. fr. 25462), Romania 40 (1911), pp. 566-570.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('78', 'Jeanroy, Alfred: Le d\1\1bat du clerc et de la damoiselle. Po\1\1me in\1\1dit du XIVe si\1\1cle, Romania, 43 (1914), pp. 1-13.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('88', 'Arthur Langfors: Notice des manuscrits 535 de la Biblioth\1\1que Municipale de Metz et 10047 des nouvelles acquisitions du Fonds Fran\1\1ais de la Biblioth\1\1que Nationale, suivie de cinq po\1\1mes fran\1\1ais sur la parabole des quatre filles de Dieu, in: Notices et extraits des manuscrits de la Biblioth\1\1que Nationale et autres biblioth\1\1ques, 42 (1933), pp. 171-292.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('89', 'Mussafia: \1\1ber eine altfranz\1\1sische Handschrift der k. Universit\1\1tsbibliothek zu Pavia, in Idem: Handschrifliche Studien', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('90', 'Langfors: Notice du manuscrit fran\1\1ais 24436 de la Biblioth\1\1que Nationale, Romania 41(1912)', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('91', 'Liborio, Mariantonia: Una versione piccarda inedita della "Visio Philiberti", in Cultura Neolatina, 33 (1973).', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('92', 'Suchier, Hermann: Oeuvres po\1\1tiques de Beaumanoir, SATF, t. 2.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('93', 'Hasenohr, Genevieve: Les traductions francaises du "Stabat mater dolorosa", in  Recherches Augustiniennes, 24 (1989).', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('94', 'Rutebeuf: Oeuvres compl\1\1tes, \1\1d. par Michel Zink, Paris, Bordas, 1989-1990.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('95', 'H\1\1ron, A.: Les dits de Hue Archevesque, trouv\1\1re normand du XIIIe si\1\1cle, Paris, 1885.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('96', 'Beaurepaire, Charles de: Complainte sur la Bataille de Poitiers, Biblioth\1\1que de l''Ecole des Chartes, 1851, pp. 257-263.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('97', 'Beaurepaire, Charles de: Complainte sur la Bataille de Poitiers, Biblioth\1\1que de l\''Ecole des Chartes, 1851, pp. 257-263.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('98', 'Beaurepaire', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('99', 'SCHNEEGANS (F. \1\1d.), Trois po\1\1mes de la fin du XIIIe si\1\1cle sur Pierre de la Broce, Romania 58 (1932), 539-542.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('100', 'The Anglo-Norman Lyric. An Antology. Edited from the Manuscripts with Translations and Commentary, eds. David L. Jeffrey, Brian J. Levy, Toronto, Pontifical Institute f Mediaeval Studies, 1990.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('101', 'Thomas Wright: The Chronicle of Pierre de Langtoft, vol. II, 1842.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('102', 'Stengel, E.: "Handschriftliches aus Oxford", Zeitschrift f\1\1r franz\1\1sische Sprache und Literatur, 14 (1892), pp. 127-160.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('103', 'Meyer, Paul: "Le Chastie-Musart d''apr\1\1s le ms. harl\1\1ien 4333", Romania 15 (1886).', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('104', 'Meyer: Le Chastie-Musart d''apres le ms. harl\1\1ien 4333, Romania 15 (1886)', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('105', 'Priebsch, J.: Zwei altfranz\1\1sische Mariengebete, in Modern Language Review 4 (1908)', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('106', 'Meyer, Paul: Le salut d''amour dans les litt\1\1ratures provencale et francaise, in Bibl. de l''\1\1cole des Chartes, 1867.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('107', 'Meyer: Le salut d''amour..., Bibl. de l''\1\1cole des Chartes, 1867', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('108', 'Jubinal, Achille: Oeuvres compl\1\1tes de Rutebeuf; trouv\1\1re du 13e si\1\1cle, 1875.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('109', 'Jubinal, Achille: Jongleurs et trouv\1\1res, Paris, 1835.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('110', 'Fant, Carl: L\1\1gende de saint Gr\1\1goire, r\1\1daction du XIVe si\1\1cle, Upsala, 1887.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('111', 'Langfors, Arthur: Dou vrai chiment d''amours. Une nouvelle source de Venus la Deesse d''amor, Romania 45 (1918-1919), 205-218.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('112', 'Otto, Richard : Altlothringische geistliche Lieder , in Romanische Forschungen , 5 (1890), 583-618.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('113', 'Priebsch, J. : Drei altlothringische Mariengebete , in Zeitschrift f\1\1r franz\1\1sische Sprache und Literatur , 33 (1908 )', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('114', 'L\1\1NGFORS, A.: Notice du manuscrit fran\1\1ais 17068 de la Biblioth\1\1que nationale, in Romania, 43 (1914), pp. 18-58.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('115', 'Esposito, Mario: Pri\1\1re anglo-normande en quatrains, in Romania 42 (1913), pp. 263-264.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('116', 'Peters, H.: Die Chronik von Floreffe, Zeitschrift f\1\1r romanische Philologie, 21 (1897)', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('117', 'Martin da Canal: Cronaca veneta, Archivo storico italiano, 1845.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('118', 'Langfors, A.: La vie de sainte de sainte Catherine, par le peintre Estienne Lanquelier, in Romania 39 (1910), pp. 54-60.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('119', 'Langfors, Arthur: Bibliographie des plaintes de la Vierge, in Revue des Langues Romanes, 53 (1910), pp. 58-69.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('120', 'Langlois: Essai sur la calligraphie des manuscrits du Mosen Age, Rouen, 1841.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('121', 'Mourin, L.: Po\1\1sies religieuses fran\1\1aises inconnues, in Scriptorium 3 (1949) pp. 218-229.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('122', 'Meyer, Paul: Deux nouveaux manuscrits de l''\1\1vangile des femmes, Romania 36 (1907), pp. 1-11.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('123', 'La guerre de Metz en 1324, po\1\1me du XIVe si\1\1cle, \1\1d. E. de Bouteiller, Paris, Firmin Didot, 1875.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('124', 'Schultz-Gora, Oskar: Ein ungedruckter Salu d''amors nebst Antwort, in Zeitschrift f\1\1r romanische Philologie, 24 (1900), 358-369.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('125', 'Piaget, Arthur: La Belle Dame sans merci et ses imitations (suite), in Romania 31 (1902), pp. 315-349.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('126', 'Guillaume de Digulleville: Le p\1\1lerinage de vie humaine / de Guillaume de Deguileville ; edited by J. J. St\1\1rzinger, London, Nichols and sons.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('127', 'Vising, Johan: Deux po\1\1mes de Nicholas Bozon. Le Char d''Orgueil. La Lettre de l''Empereur Orgueil, G\1\1teborg, 1919.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('128', 'Du M\1\1ril, Ed\1\1lstand: Po\1\1sies in\1\1dites du moyen \1\1ge, 1854.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('129', 'Langfors, Arthur: Un dit d''amours (Bibl. nat. fr. 1634), in Neuphilologische Mitteilungen, 9 (1907), pp. 5-19.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('130', 'Van Hamel, A.-G.: Li Romans de Carit\1\1 et Miserere du Renclus de Moiliens, poemes de la fin du XIIe siecle, Paris, Vieweg, 1885.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('131', 'Raynaud, Gaston: Le dit de Jean le Rigol\1\1, in Romania 7 (1878), pp. 596-599.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('132', 'Legge, M. D.: La Piere d''Escoce, Scottish Historical Review, pp. 109-113.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('133', 'Li Ver de Couloigne du bon ange et du mauves un ensaingnement, \1\1d. Hartmut Kleineidam, M\1\1nchen, Max Hueber, 1968.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('134', 'La Passiun de seint Edmund. Ein anglonormannisches gedicht aus dem 12. Jahrhundert, \1\1d. Albert Nabert, Greifswald, 1915.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('135', 'Dirickx-van der Straeten, Hermine: La Vie de saint Jehan Bouche d''Or et la Vie de sainte Dieudonn\1\1e, sa mere. Textes fran\1\1ais du moyen \1\1ge, Li\1\1ge, 1931.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('136', 'Recueil de po\1\1sies fran\1\1oises des XVe et XVIe si\1\1cles, morales, fac\1\1tieuses, historiques. Tome III / r\1\1unies et annot\1\1es par M. Anatole de Montaiglon, James de Rotschild, 1855-1878.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('137', 'Dits de Watriquet de Couvin publi\1\1s pour la premi\1\1re fois d''apr\1\1s les manuscrits de Paris et de Bruxelles et accompagn\1\1s de variantes et de notes explicatives par Aug. Scheler, Bruxelles, Devaux, 1868.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('138', 'O''Gorman, Richard: The Salut d''amour from the La Clayette Manuscript attributed to Simon, in Romance Philology, 20 (1966), pp. 39-44.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('139', 'Ruelle, Pierre: Les cong\1\1s d''Arras (Jean Bodel, Baude Fastoul, Adam de la Halle, Presses Universitaires de France, 1965.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('140', 'Reinsch, Robert: Mittheilungen aus einer franz. Handschrift des Lambeth Palace zu London, in Arhiv f\1\1r das Studium neueren Sprachen und Literaturen, 63.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('141', 'Langfors, Arthur: Notice du manuscrit fran\1\1ais 12483 de la Biblioth\1\1que Nationale, Notices et extraits de manuscrits, 39/1 (1909), 502-662.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('142', 'Courtois d''Arras. Jeu du XIIIe si\1\1cle, \1\1d. Edmond Faral, Paris, Champion', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('143', 'Le Contenz dou monde by Renaud d\1\1\1Andon, \1\1d. T. Atkinson Jenkins, in\1\1: Studies in honor of A. Marshall Elliott, 1911. I, pp. 53-79.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('144', 'Thomas Maillet (?): Les Proverbez d''Alain, ed. Tony Hunt, Les Classiques francais du Moyen Age (Paris: Honore Champion, 2007).', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('145', 'Valkhoff, Marius: Le manuscrit 76 G 17 de La Haye et l''ancienne hymne wallonne, Romania 62 (1936), pp. 17-26.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('146', 'Morawski, Jean: Le Facet en fran\1\1oys, Poznan, 1923.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('147', 'Thilois, M. Bulletin de la Soci\1\1t\1\1 acad\1\1mique de Laon, t. X (1860)', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('148', 'Paris, Paulin: Les grandes chroniques de France, 1838, vol. 6', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('149', 'Meyer, Paul: Le savetier baillet. Chanson comique, Romania, 3 (1874), pp. 103-106. ', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('150', 'Gautier de Coinci: Les Miracles de Nostre Dame, \1\1d. Fr\1\1d\1\1ric V. Koenig, Gen\1\1ve, 1955-70', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('151', 'Meyer, Paul: \1\1 Pri\1\1res et po\1\1sies religieuses tir\1\1es d''un manuscrit lorrain ( Arsenal 570) \1\1, Bulletin de la Soci\1\1t\1\1 des anciens textes fran\1\1ais, 27, 1901, pp. 43-80.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('152', 'L\1\1ngfors, Arthur: \1\1\1\1Notice et extraits du manuscrit Additional 44949 du Mus\1\1e Britannique\1\1\1\1, Neuphilologische Mitteilungen, 49 (1948), pp. 97-123.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('153', 'R\1\1zeau, Pierre: Les pri\1\1res aux saints en fran\1\1ais \1\1 la fin du moyen \1\1ge, Gen\1\1ve, Droz, 1982.', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('200', 'Recueil des historiens des Gaules et de la France, \1\1d. Dom Martin Bouquet, vol. 23.', 'Sz\1\1vegkiad\1\1sok');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('201', 'Recueil g\1\1n\1\1ral et complet des fabliaux des XIIIe et XIVe si\1\1cles. T. 1 / publ. par M.M. Anatole de Montaiglon et Gaston Raynaud, Paris, Librairie des bibliophiles, 1872-1890.', 'Sz\1\1vegkiad\1\1sok');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('202', 'Complainte ou \1\1l\1\1gie romane sur la mort de Enguerrant de Cr\1\1qui, \1\1v\1\1que de Cambrai, publi\1\1e par Edward Le Glay, Paris, 1834.', 'Sz\1\1vegkiad\1\1sok');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('203', 'Extraits de plusieurs petits po\1\1mes \1\1crits \1\1 la fin du XIVe si\1\1cle par un prieur du Mont Saint-Michel; Caen, 1837.', 'Sz\1\1vegkiad\1\1sok');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('52', 'Jeanroy, Alfred: Trois dits d''amour du XIIIe si\1\1cle, Romania 22 (1893)', 'edition');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('204', 'Etienne de Fougeres, Le livre des Manieres, \1\1d. R. Anthony Lodge, Gen\1\1ve, Droz, 1979.', 'Sz\1\1vegkiad\1\1sok');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('205', 'Ansch\1\1tz, August: Bruhst\1\1ck eines lateinischen Marienliedes mit altfranz\1\1sischer \1\1bersetzung, in: Zeitschrift f\1\1r Deutsche Philologie 1 (1869), p. 178-180.', 'Sz\1\1vegkiad\1\1sok');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('206', 'Lecompte, I. C.: Le fablel dou dieu d''amours, in: Modern Philology, 8 (1910), 63-86.', 'Sz\1\1vegkiad\1\1sok');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('207', 'Paris, Gaston - Pannier, L\1\1opold: La vie de saint Alexis. Textes des XIe, XIIe, XIIIe, et XIVe si\1\1cles, Paris, 1972.', 'Sz\1\1vegkiad\1\1sok');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('208', '\1\1milie Goudot: Gilles le Muisit: Registre. \1\1dition des neuf premiers chapitres du texte, d\1\1\1apr\1\1s le manuscrit Br IV 119 de la Biblioth\1\1que Royale de Bruxelles', 'Sz\1\1vegkiad\1\1sok');
INSERT INTO "bibliok" ("b_index", "biblio", "tipus") VALUES ('209', 'Kastner, L. E.: Le Songe. Poeme all\1\1gorique et religieux du XIIIe siecle', 'Sz\1\1vegkiad\1\1sok');

-- Indexes

CREATE UNIQUE INDEX bibliok_pkey ON bibliok USING btree (b_index);
