-- MySQL Script generated by MySQL Workbench
-- Sex 03 Fev 2017 13:33:38 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`auteur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`auteur` (
  `a_index` INT(11) NOT NULL,
  `auteur` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `born` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  `dead` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  `soc_status` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  `active_from` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  `active_to` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`a_index`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `mydb`.`biblio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`biblio` (
  `b_index` INT(11) NOT NULL,
  `biblio` TEXT CHARACTER SET 'utf8' NOT NULL,
  `tipus` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`b_index`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `mydb`.`strofak`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`strofak` (
  `s_index` INT(11) NOT NULL,
  `s_szam` INT(11) NOT NULL,
  `s_ertek` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `v_index` INT(11) NOT NULL,
  `c_szandekos` CHAR(1) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`s_index`),
  INDEX `v_index` (`v_index` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `mydb`.`versek`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`versek` (
  `m_index` INT(11) NOT NULL,
  `incipit` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`m_index`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `mydb`.`valtozatok`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`valtozatok` (
  `v_index` INT(11) NOT NULL,
  `m_index` INT(11) NOT NULL,
  `old_m_contexte9` TEXT CHARACTER SET 'utf8' NOT NULL,
  `old_m_contexte90` TEXT CHARACTER SET 'utf8' NOT NULL,
  `old_i_contexte91` INT(11) NOT NULL,
  `old_i_contexte92` INT(11) NOT NULL,
  `old_i_contexte93` INT(11) NOT NULL,
  `old_i_contexte94` INT(11) NOT NULL,
  `old_i_contexte95` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `old_i_contexte96` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `old_i_contexte97` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `s_contexte8` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `s_emplacement` INT(11) NULL DEFAULT NULL,
  `old_s_contexte1` INT(11) NULL DEFAULT NULL,
  `old_s_contexte2` INT(11) NULL DEFAULT NULL,
  `s_versification1` INT(11) NULL DEFAULT NULL,
  `s_versification2` INT(11) NULL DEFAULT NULL,
  `s_versification3` INT(11) NULL DEFAULT NULL,
  `s_metre` INT(11) NULL DEFAULT NULL,
  `c_cesure` INT(11) NULL DEFAULT NULL,
  `c_refrain` INT(11) NULL DEFAULT NULL,
  `s_timbres1` INT(11) NULL DEFAULT NULL,
  `s_timbres2` INT(11) NULL DEFAULT NULL,
  `s_timbres3` INT(11) NULL DEFAULT NULL,
  `s_gonisme` INT(11) NULL DEFAULT NULL,
  `s_musique` INT(11) NULL DEFAULT NULL,
  `s_niveau` INT(11) NULL DEFAULT NULL,
  `s_fonction` INT(11) NULL DEFAULT NULL,
  `s_usage` INT(11) NULL DEFAULT NULL,
  `c_caractere` INT(11) NULL DEFAULT NULL,
  `s_mise` INT(11) NULL DEFAULT NULL,
  `s_langue` INT(11) NULL DEFAULT NULL,
  `c_titre` VARCHAR(16) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `m_rubrique` VARCHAR(16) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `m_auteur` VARCHAR(16) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `m_auteurs` VARCHAR(16) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `m_genre` VARCHAR(16) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `m_outils` VARCHAR(16) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_bibliographie` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `s_timbres4` SMALLINT(6) NULL DEFAULT NULL,
  `s_timbres5` SMALLINT(6) NULL DEFAULT NULL,
  `s_timbres6` SMALLINT(6) NULL DEFAULT NULL,
  `s_timbres7` SMALLINT(6) NULL DEFAULT NULL,
  `s_timbres8` SMALLINT(6) NULL DEFAULT NULL,
  `s_timbres9` SMALLINT(6) NULL DEFAULT NULL,
  `s_timbres10` SMALLINT(6) NULL DEFAULT NULL,
  `i_titre3` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `old_i_manuscrit` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `t_incipit` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_titre1` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_titre2` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_titre4` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_titre5` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_titre_rem` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_emlacement` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_contexte_rem` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_rubrique1` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_rubrique2` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_concordance1` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_concordance2` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_concordance3` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_auteur1` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_auteur2` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_auteur3` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_auteur4` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_auteur6` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_auteur7` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_auteur8` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_auteur9` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_auteur10` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_versification1` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_versification2` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_versification3` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_versification4` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_versi_rem` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_cesure` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_refrain` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_metre_rem` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_abstraction` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_strophe` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_timbres1` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_timbres2` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_timbres3` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_proportion` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_arany_f` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_arany_m` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_gonisme_rem` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_mod_litteraire` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_mod_metrique` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_mod_melodique` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_genre1` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_genre2` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_genre3` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_genre4` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_genre5` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_public1` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_public2` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_outils1` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_outils2` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_outils3` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_outils4` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_outils5` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_outils6` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_outils7` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_outils8` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_outils9` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_outils10` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_outils11` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_outils12` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_auteurs1` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_auteurs2` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_auteurs3` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_auteurs4` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_edition` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_timbres4` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_timbres5` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_timbres6` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_timbres7` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_timbres8` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_timbres9` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_timbres10` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_concordance4` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_concordance5` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_imit_litteraire` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_imit_metrique` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_imit_melodique` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `s_contexte7` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `s_edition` BIGINT(20) NULL DEFAULT NULL,
  `s_langue_dialecte` BIGINT(20) NULL DEFAULT NULL,
  `old_i_contexte98` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `old_i_contexte99` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `kitoltottseg` INT(11) NULL DEFAULT NULL,
  `s_auteur1` SMALLINT(6) NULL DEFAULT NULL,
  `s_auteur2` SMALLINT(6) NULL DEFAULT NULL,
  `s_auteur3` SMALLINT(6) NULL DEFAULT NULL,
  `s_auteur4` SMALLINT(6) NULL DEFAULT NULL,
  `s_auteur5` SMALLINT(6) NULL DEFAULT NULL,
  `s_auteur6` SMALLINT(6) NULL DEFAULT NULL,
  `s_auteur7` SMALLINT(6) NULL DEFAULT NULL,
  `s_auteur8` SMALLINT(6) NULL DEFAULT NULL,
  `s_auteur9` SMALLINT(6) NULL DEFAULT NULL,
  `s_auteur10` SMALLINT(6) NULL DEFAULT NULL,
  `i_auteur1_rem` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_auteur2_rem` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_auteur3_rem` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_auteur4_rem` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_auteur5_rem` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_auteur6_rem` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_auteur7_rem` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_auteur8_rem` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_auteur9_rem` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_auteur10_rem` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `s_datedumanuscrit` INT(11) NULL DEFAULT NULL,
  `m_fragmentaire` VARCHAR(10) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_abstraction_rimes` VARCHAR(100) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_abstraction_structure` VARCHAR(100) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `m_gonisme_melange` VARCHAR(10) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `s_gonisme_melange` VARCHAR(10) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `c_gonisme_melange` VARCHAR(10) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `s_kolophon` INT(11) NULL DEFAULT NULL,
  `i_kolophon` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_mise_rem` VARCHAR(250) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `m_caractere` VARCHAR(250) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `manuscrit_id` INT(11) NULL DEFAULT NULL,
  `i_caractere_5` VARCHAR(250) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_outils1b` VARCHAR(250) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_genre6` VARCHAR(250) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `s_outils1b` VARCHAR(100) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `c_metre_syllabique` INT(11) NULL DEFAULT NULL,
  `i_metre_syllabique` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `s_metre_syllabique` INT(11) NULL DEFAULT NULL,
  `i_versification_nombre_vers` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_outils1b_rem` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_concordance6` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_concordance7` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `i_concordance8` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`v_index`),
  INDEX `m_index` (`m_index` ASC),
  CONSTRAINT `valtozatok_ibfk_1`
    FOREIGN KEY (`v_index`)
    REFERENCES `mydb`.`strofak` (`v_index`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `valtozatok_ibfk_2`
    FOREIGN KEY (`m_index`)
    REFERENCES `mydb`.`versek` (`m_index`),
  CONSTRAINT `fk_valtozatok_1`
    FOREIGN KEY ()
    REFERENCES `mydb`.`biblio` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `mydb`.`datalas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`datalas` (
  `d_index` INT(11) NOT NULL,
  `d_sorszam` INT(11) NOT NULL,
  `d_elso` VARCHAR(5) CHARACTER SET 'utf8' NOT NULL,
  `d_masodik` VARCHAR(5) CHARACTER SET 'utf8' NOT NULL,
  `d_tipus` VARCHAR(5) CHARACTER SET 'utf8' NOT NULL,
  `v_index` INT(11) NOT NULL,
  PRIMARY KEY (`d_index`),
  INDEX `v_index` (`v_index` ASC),
  CONSTRAINT `datalas_ibfk_1`
    FOREIGN KEY (`v_index`)
    REFERENCES `mydb`.`valtozatok` (`v_index`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `mydb`.`dialecte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dialecte` (
  `d_index` INT(11) NOT NULL,
  `dialecte` TEXT CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`d_index`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `mydb`.`edition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`edition` (
  `e_index` INT(11) NOT NULL,
  `edition` TEXT CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`e_index`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `mydb`.`kapcsolatok`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`kapcsolatok` (
  `k_index` INT(11) NOT NULL,
  `m_index` BIGINT(20) NOT NULL,
  `egyeb` TEXT CHARACTER SET 'utf8' NOT NULL,
  `tipus` TEXT CHARACTER SET 'utf8' NOT NULL,
  `v_index` BIGINT(20) NOT NULL,
  PRIMARY KEY (`k_index`),
  INDEX `m_index` (`m_index` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `mydb`.`outils1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`outils1` (
  `ou_index` INT(11) NOT NULL,
  `title` INT(11) NOT NULL,
  PRIMARY KEY (`ou_index`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `mydb`.`t_jiaozhu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_jiaozhu` (
  `jiaozhu` VARCHAR(200) CHARACTER SET 'utf8' NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `mydb`.`verselesek`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`verselesek` (
  `ve_index` INT(11) NOT NULL,
  `strofaszam` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
  `absztrakcio` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `incipit` TEXT CHARACTER SET 'utf8' NOT NULL,
  `v_index` INT(11) NOT NULL,
  PRIMARY KEY (`ve_index`),
  INDEX `v_index` (`v_index` ASC),
  CONSTRAINT `verselesek_ibfk_1`
    FOREIGN KEY (`v_index`)
    REFERENCES `mydb`.`valtozatok` (`v_index`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
