SET SESSION AUTHORIZATION 'p-nouve';

SET search_path = "backup", pg_catalog;

-- Definition

-- DROP TABLE "backup"."valtozatok_bkp";
CREATE TABLE "backup"."valtozatok_bkp" (
    "v_index" integer,
    "m_index" integer,
    "old_m_contexte9" text,
    "old_i_contexte90" text,
    "old_i_contexte91" text,
    "old_i_contexte92" text,
    "old_i_contexte93" text,
    "old_i_contexte94" text,
    "old_i_contexte95" text,
    "old_i_contexte96" text,
    "old_i_contexte97" text,
    "s_contexte8" text,
    "s_emplacement" integer,
    "old_s_contexte1" integer,
    "old_s_contexte2" integer,
    "s_versification1" integer,
    "s_versification2" integer,
    "s_versification3" integer,
    "s_metre" integer,
    "c_cesure" integer,
    "c_refrain" integer,
    "s_timbres1" integer,
    "s_timbres2" integer,
    "s_timbres3" integer,
    "s_gonisme" integer,
    "s_musique" integer,
    "s_niveau" integer,
    "s_fonction" integer,
    "s_usage" integer,
    "c_caractere" integer,
    "s_mise" integer,
    "s_langue" integer,
    "c_titre" character varying(16),
    "m_rubrique" character varying(16),
    "m_auteur" character varying(16),
    "m_auteurs" character varying(16),
    "m_genre" character varying(16),
    "m_outils" character varying(16),
    "i_bibliographie" text,
    "s_timbres4" smallint,
    "s_timbres5" smallint,
    "s_timbres6" smallint,
    "s_timbres7" smallint,
    "s_timbres8" smallint,
    "s_timbres9" smallint,
    "s_timbres10" smallint,
    "i_titre3" text,
    "old_i_manuscrit" text,
    "t_incipit" text,
    "i_titre1" text,
    "i_titre2" text,
    "i_titre4" text,
    "i_titre5" text,
    "i_titre_rem" text,
    "i_emlacement" text,
    "i_contexte_rem" text,
    "i_rubrique1" text,
    "i_rubrique2" text,
    "i_concordance1" text,
    "i_concordance2" text,
    "i_concordance3" text,
    "i_auteur1" text,
    "i_auteur2" text,
    "i_auteur3" text,
    "i_auteur4" text,
    "i_auteur6" text,
    "i_auteur7" text,
    "i_auteur8" text,
    "i_auteur9" text,
    "i_auteur10" text,
    "i_versification1" text,
    "i_versification2" text,
    "i_versification3" text,
    "i_versification4" text,
    "i_versi_rem" text,
    "i_cesure" text,
    "i_refrain" text,
    "i_metre_rem" text,
    "i_abstraction" text,
    "i_strophe" text,
    "i_timbres1" text,
    "i_timbres2" text,
    "i_timbres3" text,
    "i_proportion" text,
    "i_arany_f" text,
    "i_arany_m" text,
    "i_gonisme_rem" text,
    "i_mod_litteraire" text,
    "i_mod_metrique" text,
    "i_mod_melodique" text,
    "i_genre1" text,
    "i_genre2" text,
    "i_genre3" text,
    "i_genre4" text,
    "i_genre5" text,
    "i_public1" text,
    "i_public2" text,
    "i_outils1" text,
    "i_outils2" text,
    "i_outils3" text,
    "i_outils4" text,
    "i_outils5" text,
    "i_outils6" text,
    "i_outils7" text,
    "i_outils8" text,
    "i_outils9" text,
    "i_outils10" text,
    "i_outils11" text,
    "i_outils12" text,
    "i_auteurs1" text,
    "i_auteurs2" text,
    "i_auteurs3" text,
    "i_auteurs4" text,
    "i_edition" text,
    "i_timbres4" text,
    "i_timbres5" text,
    "i_timbres6" text,
    "i_timbres7" text,
    "i_timbres8" text,
    "i_timbres9" text,
    "i_timbres10" text,
    "i_concordance4" text,
    "i_concordance5" text,
    "i_imit_litteraire" text,
    "i_imit_metrique" text,
    "i_imit_melodique" text,
    "s_contexte7" text,
    "s_edition" bigint,
    "s_langue_dialecte" bigint,
    "old_i_contexte98" character varying(255),
    "old_i_contexte99" character varying(255),
    "kitoltottseg" integer,
    "s_auteur1" smallint,
    "s_auteur2" smallint,
    "s_auteur3" smallint,
    "s_auteur4" smallint,
    "s_auteur5" smallint,
    "s_auteur6" smallint,
    "s_auteur7" smallint,
    "s_auteur8" smallint,
    "s_auteur9" smallint,
    "s_auteur10" smallint,
    "i_auteur1_rem" text,
    "i_auteur2_rem" text,
    "i_auteur3_rem" text,
    "i_auteur4_rem" text,
    "i_auteur5_rem" text,
    "i_auteur6_rem" text,
    "i_auteur7_rem" text,
    "i_auteur8_rem" text,
    "i_auteur9_rem" text,
    "i_auteur10_rem" text,
    "s_datedumanuscrit" integer,
    "m_fragmentaire" character varying(10),
    "i_abstraction_rimes" character varying(100),
    "i_abstraction_structure" character varying(100),
    "m_gonisme_melange" character varying(10),
    "s_gonisme_melange" character varying(10),
    "c_gonisme_melange" character varying(10),
    "s_kolophon" integer,
    "i_kolophon" character varying(255),
    "i_mise_rem" character varying(250),
    "m_caractere" character varying(250),
    "manuscrit_id" integer,
    "i_caractere_5" character varying(250),
    "i_outils1b" character varying(250),
    "i_genre6" character varying(250),
    "s_outils1b" character varying(100),
    "c_metre_syllabique" integer,
    "i_metre_syllabique" text,
    "s_metre_syllabique" integer,
    "i_versification_nombre_vers" text,
    "i_outils1b_rem" text,
    "i_concordance6" text,
    "i_concordance7" text,
    "i_concordance8" text
) WITHOUT OIDS;

